all: HW002

HW002:
	g++ -c -std=c++0x Circle.cpp
	g++ -c -std=c++0x Triangle.cpp
	g++ -c -std=c++0x Rectangle.cpp
	g++ -c -std=c++0x ComposedShapes.cpp
	g++ -c -std=c++0x main.cpp
	g++ -o HW002 Circle.o Triangle.o Rectangle.o ComposedShapes.o main.o

clean:
	rm *.o HW002
